### ISSUE TITLE
New options

### ISSUE THREAD

**Issue by AlbaPi** [TheRosettaFoundation/SOLAS-Match#1098]
I think it would be extremely useful, we had the option to assign a task to a volunteer and upload a document for them. Do you think it would be easy to let us have the option to do it ourselves? 

Thank you so much!

**Comment by Paulina-Rosetta** [comment]
@spaceindaver Dave, after your helpful contribution yesterday I was hoping you might  be able to help here too :-) Would this be difficult to implement?

**Comment by spaceindaver** [comment]
Hey, it should be pretty easy to implement. You would need an interface for the admins to do it though. This could be added to the admin page or maybe the task view page (if you are an admin). I'm not sure how you identify users but their ID seems like the easiest way to assign something to a user. As for uploading a task, I think you can already do that. You should be able to access the task upload page as an admin and upload the file they gave you. As far as I remember, an admin can do anything and is not restricted by user priviledges.

I will say, however, that this kind of behaviour should be avoided as much as possible since it is not scalable. If the site had one million monthly active users then you would need an army of admins to manage the tasks. This would be no better than the SharePoint implementation Solas Match replaced so improving existing systems to make them easier for people to use should be the higher priority. Maybe you could identify the common faults with the system that prevents users from claiming and uploading tasks themselves and fix that instead so that this functionality is not required.

**Comment by Paulina-Rosetta** [comment]
Thanks Dave! Yes - I remember the discussions we had about this previously and I do agree. The thing is that we waste a lot of the developers time these asking them to assign tasks so it's really a short-term objective but needed nonetheless. Really appreciate you helping out!

**Comment by Wasala** [comment]
I've implemented the first part of this request. When Admins click on an unclaimed task from the task-stream(i.e. on a link like trommons.org/task/xx/id/), they will see an input box where they can enter either an ID or email of an existing user. After verifying whether the task has not been blacklisted for the given user, the task will be assigned to that user (and appropriate emails should also get sent). I will close this issue as the second part of the request (uploading the files) can already be done by the admins as per Dave's comment above.
