### ISSUE TITLE
Implement a scalable mechanism to easily localise static content found in the database - e.g. System Badges

### ISSUE THREAD

**Issue by Wasala** [TheRosettaFoundation/SOLAS-Match#1129]
A scalable mechanism needs to be implemented to facilitate the localisation of some static strings found in the database such as System badges and their descriptions. 

The proposed idea is to develop a function such as getTranslationForDBString($string) which will do the following operations:
1) get the string
2) hash it (e.g. using sha1)
3) search the strings.xml file of the target locale for a string where the name of the string ends with the above hash
4) if found a matching string, use that in place of the string returned by the db
5) if not found, use the original string (from the db)

e.g.  getTranslationForDBString("SOLAS Match - Registered") 
1) string =  "SOLAS Match - Registered"
2) hash/encoded string = 9r9yhyc4uv40c8occog84s408ssk448
3) search in strings file of the current locale for an entry like

```
< string name="db_string_badges_registered_9r9yhyc4uv40c8occog84s408ssk448" > translation </string>
```
4) found a translation, so function returns the translation

The above mechanism is scalable to a certain degree and allows meaningful keys for the strings file entry. In this manner, the database needs not to be altered to have separate columns for each language and same strings.xml file can be used to localise some static content in the db. The disadvantage is that if an entry in the database is changed, the keys in the strings.xml file needs to be changed too.

However, the above mechanism is not practical for localising content such as the county list as collation/sorting order of entries needs to be taken into account when presenting these to the user.

**Comment by spaceindaver** [comment]
Hey @Wasala, this is a very common problem in software localisation. Again, I don't see why you want to make a new solution to a problem when one already exists for the system. The simple solution is to change the DB to use loctags (by loctag I mean the "name" attribute in the strings.xml file) and call get translation on that. This system is already in place and would be very easy to implement.

I do agress that hashing is a good way to speed things up since the string comparrisons you are doing at the moment are very inefficient. However, it is not a good idea to use the string itself to generate the hash. The common solution to this problem is to write a tool to convert the strings.xml file into a new XML file that replaces all the "name" attribute values with the a hashed version of that value. Then, in the getTranslation function, you hash the requested string and search for that instead. Then, you could load the XML into a hash map to get the performance benefit. This is exactly how we do it in our games and I am sure it is the most common method of software localisation in use (unless you have a trivial number of strings in which case you can take the performance hit of string comparrisons).

The main advantage of using loctags is that they are entirely independent of the string itself. This means the string can change and you don't need to update the hash tables. The solution you suggested has all the disadvantages of the current system but is missing several advantages. Simply switching the DB to use loctags would be a much better solution. Using hashes and adding everything to a hash map at runtime would be an even better solution but would take a while to develop (you would need to develop a tool that does the hashing for you, stores off the generated XML, load the new hashed XML instead of the raw one being used now and add hashing logic to the getTranslation function).

**Comment by Wasala** [comment]
Hi @spaceindaver, Can you please elaborate on how exactly can I implement your proposed solution:
"The simple solution is to change the DB to use loctags (by loctag I mean the "name" attribute in the strings.xml file) and call get translation on that. ":

You mean to hard-code the loctags in place of the English strings in the database and use getTranslation() function?

Yeah.. I do agree the implementation of a hash map is better to speed up the l10n.

**Comment by TheIceMageX50** [comment]
@Wasala I think that's what @spaceindaver was getting at, yea. Putting the loctags in the DB in place of the English strings does sound like a nice and quick solution.

**Comment by Wasala** [comment]
@spaceindaver @TheIceMageX50 I will go for it :smile:

**Comment by spaceindaver** [comment]
@TheIceMageX50, yeah, thats exactly when I meant :-)
