### ISSUE TITLE
An organisation has disappeared

### ISSUE THREAD

**Issue by AlbaPi** [TheRosettaFoundation/SOLAS-Match#1152]
ABColombia has disappeared. Could you rescue it?

**Comment by Wasala** [comment]
Very strange. Do you know since when?

**Comment by AlbaPi** [comment]
This morning was on the "Dashboard". Maybe it's since a new organisation has created (Diakonie Katastrophenhilfe Regional Office ASIA). ABColombia was the first of the list. 

We have also recevied when the new organisation has created: You have successfully created the organisation ABColombia on Trommons. As the creator of this organisation you have been made the organisation administrator. This gives you slightly more control over the organisation than other members. Please visit the organisation's public profile where you can alter the organisations details and add new members.

**Comment by Wasala** [comment]
I can easily re-create the ABColombia using previous database backups. But do you know whether they had any active projects/tasks in the system?

**Comment by Wasala** [comment]
It seems like ABComlombia has been wiped off from the system with all data related to it. While re-creating the org is easy enough, brining back all the related data is very difficult. What has happened is equivalent to deleting the org. So can you confirm the following:

a) whether they have intentionally or accidentally deleted their org? 
b) re-creating org is just sufficient? (i.e. not to recover related data)

**Comment by AlbaPi** [comment]
They didn’t have any active project. I’ll ask ABColombia about that.

**Comment by Wasala** [comment]
That's great Alba. I will wait until you get back to me on this.

**Comment by AlbaPi** [comment]
We think that when a new organisation registers on Trommons, it become automatically a member of the first organisation on the list on Trommons. Moreover, the organisation and the administrators receive an e-mail that an organisation has been created.

**Comment by AlbaPi** [comment]
ABColombia said that they should have all the recent projects saved. If you can, you could recreate the organisation.

**Comment by Wasala** [comment]
Will do.

**Comment by Wasala** [comment]
Already restored the org, but not its data. I will send you some info via email as to what might have happened.

**Comment by Wasala** [comment]
Temporarily prevented random orgs getting deleted while new ones are being created by commenting out the org deletion part here: https://github.com/TheRosettaFoundation/SOLAS-Match/blob/master/api/v0/Orgs.php#L370 

@spaceindaver any idea why do you want to perform the above check?

**Comment by spaceindaver** [comment]
There must be a bug in there somewhere. The idea is that when creating an organisation you must add the user that created it as both a member and an admin. If any of those operations failed then you should roll back the DB to the state it was in before the API request. The best way to do this is to delete the org that was just created since that will also delete all associated data thereby leaving the DB in the same state it was in before the API call. Something strange must be going on since the $org->getId() function should only return the ID of the newly created org. I don't understand how it deleted a totally different organisation. You should check the DB procedure for creating an organisation to make sure it returns the newly created table entry for that Org and check the delete procedure to make sure it only deletes an entry if it was found and doesn't delete arbitrary organisations.

The API function looks fine, it must be a bug somewhere else.

**Comment by Wasala** [comment]
These are my findings:
* I could not replicate this issue in my local machine.
* CreateOrg code is messy. It involves calling the same function over and over again in number of places. 
* Ended up calling DB with the following to retrieve the org just created:
```
CALL getOrg(LAST_INSERT_ID(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 
```
* So the problem can be due to LAST_INSERT_ID() not returning the just created org.
* Since the org names are unique, getting the org by name might resolve the issue (and I will try implementing that)

In the following I have listed how I have traced the issue:

UI call - https://github.com/TheRosettaFoundation/SOLAS-Match/blob/master/ui/RouteHandlers/OrgRouteHandler.class.php#L97 

UI/DAO:
https://github.com/TheRosettaFoundation/SOLAS-Match/blob/master/ui/DataAccessObjects/OrganisationDao.class.php#L99

calls the API:
```
request = "{$this->siteApi}v0/orgs";
$ret = $this->client->call(\SolasMatch\Common\Protobufs\Models\Organisation",$request,Common\EnumsHttpMethodEnum::POST,$org);
```
and creates the org admin:

https://github.com/TheRosettaFoundation/SOLAS-Match/blob/master/ui/DataAccessObjects/OrganisationDao.class.php#L113

=================
API: https://github.com/TheRosettaFoundation/SOLAS-Match/blob/master/api/v0/Orgs.php#L352
CreateOrg()

```
$org = DAO\OrganisationDao::insertAndUpdate($data);
if (!is_null($org) && $org->getId() > 0) {
            DAO\OrganisationDao::acceptMemRequest($org->getId(), $user->getId());
            DAO\AdminDao::addOrgAdmin($user->getId(), $org->getId());
            if (!DAO\AdminDao::isAdmin($user->getId(), $org->getId())) {
                DAO\OrganisationDao::delete($org->getId());
            }
}
```

database:
https://github.com/TheRosettaFoundation/SOLAS-Match/blob/master/db/schema.sql#L3825
```
INSERT INTO Organisations ( name, biography, `home-page`, `e-mail`, address, city, country, `regional-focus`) 
                values ( companyName, bio, url, email, address, city, country, regionalFocus);

		CALL getOrg(LAST_INSERT_ID(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
```

calls acceptMemRequest and addOrgAdmin again and immediately check whether the added admin is not the org's admin, if not delete the org.

API/DAO/addOrgAdmin()

https://github.com/TheRosettaFoundation/SOLAS-Match/blob/master/api/DataAccessObjects/AdminDao.class.php#L87

Call the accept membership function again and add the admin.
```
OrganisationDao::acceptMemRequest($orgId, $userId);
```

**Comment by Wasala** [comment]
Finally I could trace down the issue. Whenever someone attempts to create an org with an existing name, the database returns first org (when alphabetically listed). Although the user get an error saying an org already exists, the code proceeds with the erroneously returned org. 

Fixed this issue and cleaned up the code.

**Comment by Paulina-Rosetta** [comment]
@alanbarrett

**Comment by alanbarrett** [comment]
This problem (or at least a version of it) reoccurred. When an organisation is created, the user is added as an Admin of a different organisation and the email is sent to the wrong person.

Commit a0cd5b6f93c242f26549bde49efadeac016443af fixes this.

The parameter list to the MySQL stored procedure getOrg (and also getTask) has the wrong size of VARCHAR. So if an organisation name is greater that 50, after Organisation creation bad data is returned because the passed truncated name does not match the name of the newly created organisation.

The returned id is used for a number of things, which all then fail to operate correctly...
- New Admin is added to wrong organisation.
- Notification email is sent to wrong person.
- Extended Profile is attached to wrong Organisation.

    Alan.
