### ISSUE TITLE
Org members can't view volunteer profiles

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#1203]
When org members click on a link to a volunteer profile they get the following error:

XML Parsing Error: syntax error Location: http://trommons.org/4842/profile/ Line Number 2, Column 1:
Fatal error: Call to a member function getLanguagePreference() on a non-object in /repo/solas-match/ui/RouteHandlers/UserRouteHandler.class.php on line 1003
^

I think the idea was that they should be able to view the username and bio but not the email adress and other contact details. I thought I rembered that there were two links to a user profile, one public and one private, but I'm not sure now. When a user claims a task, the org gets an email inviting them to view the profile, so something needs to be fixed here:

A task that you are following on Trommons has changed its status. The "Translation" task for "Power of Attorney document" from Spanish into English has been claimed by Shivaugn. You can visit the translator's public profile *here*. You will be informed when a translation becomes available.
From, 
The Trommons Team

**Comment by alanbarrett** [comment]
I can fix this. But I need to know exactly what on that page should or should not be seen...

Display Name
E-Mail
Native Language
Secondary Language(s)
Biography
Language Preference
First Name
Last Name
City
Country
Badges
Tags
Organisations
Archived Tasks

**Comment by Paulina-Rosetta** [comment]
Ok I've opened a can of worms here. In our intro video we tell volunteers that only their display name will be publically visible. On the other hand, some volunteers have asked for a public profile that they can use to promote their volunteering work. Any thoughts on this @AlbaPi @reinhardschaler @Wasala @spaceindaver @SeanMooney @TheIceMageX50 ?

**Comment by Wasala** [comment]
Related #22, #10

**Comment by Paulina-Rosetta** [comment]
@Wasala Re the  ‘Receive Credit’ option (http://trommons.org/static/faq/#vol_q_will_my_work_credited) - has this been implemented so that names are visibible to organisations?

**Comment by Wasala** [comment]
@Paulina-Rosetta I had a quick look at:#940 and #795, 4125cedf3a8df471f7a53034c14e7bd5e116108  , https://github.com/TheRosettaFoundation/SOLAS-Match/blob/master/ui/RouteHandlers/UserRouteHandler.class.php#L929 and https://github.com/TheRosettaFoundation/SOLAS-Match/blob/master/ui/templating/templates/user/user-public-profile.tpl#L13. It seems like user's public profile does not use "Receive Credit" option when displaying user names.

**Comment by Paulina-Rosetta** [comment]
@alanbarrett hope this helps. Thanks Asanka!

**Comment by Wasala** [comment]
@Paulina-Rosetta @alanbarrett I like the idea of allowing users to showcase their activity on Trommons (task history) through the public profile. This is backed by previous research too (for example: http://arxiv.org/ftp/arxiv/papers/1204/1204.3724.pdf). 

p.s.
I'll email Alan a presentation called "User Reputation System for SOLAS" that I had prepared in 2013 that proposes this idea along with some more ideas for improving Trommons.

**Comment by alanbarrett** [comment]
As regards the public profile I will make this work but hide...
E-Mail
First Name
Last Name
Organisations
Archived Tasks

I will display...
Display Name
Native Language
Secondary Language(s)
Biography (when discussing with Paulina, I thought not to include this... but this is the only place it can be used, otherwise it will never display)
Language Preference (probably)
City (when discussing with Paulina, I thought not to include this... but I think it makes sense and should not be too intrusive, also this is the only place it can be used, otherwise it will never display)
Country
Badges (probably)
Tags (possibly)

With respect to "Receive Credit", it seems that it is used in (at least two places) 
1) Reference email- set user's First and Last name instead of display name. If display name is not set, default to display name.
2) Organisations- making user's name available on the download page if they have ticked that box on their profile.
see... https://github.com/TheRosettaFoundation/SOLAS-Match/issues/795 ( getUserRealName )

    Alan.

**Comment by alanbarrett** [comment]
Do we need to notify users that their City, Country and Bio will be displayed?

    Alan.

**Comment by alanbarrett** [comment]
Actually, on looking at the existing code, I will try to follow the original intention which does not display the following...
E-Mail
First Name
Last Name
Language Preference
City
Country

But, I think, does display...
Biography
Badges
Tags
Organisations
Archived Tasks

    Alan.

**Comment by alanbarrett** [comment]
Done!

    Alan.

**Comment by Paulina-Rosetta** [comment]
Thanks Alan!

**Comment by alanbarrett** [comment]
In response to a Query by Paulina...

I have now rechecked the code and did an experiment to see could I edit someone else's profile which I could not.

The code is pretty clear that only the user themselves or a site-wide admin can see the ones you mentioned...
E-Mail
First Name
Last Name
Language Preference
City
Country

Display name is displayed publicly, by the way, although I did not mention that in the post you reference.

If you wanted to you could try to test as an ordinary user if you could see the private data, but the code is fairly clear and I am sure I would have tested as part of my reworking of that code.

What is not so clear is how the code protects editing of someone else's profile e.g. on the test server... http://loc.csisdmz.ul.ie/SOLAS-Match/43/privateProfile/

However it seems to protect this by crashing the page with an error. Which is not a very clean way of doing it...  but since they would have to get to that page by playing tricks, that is not a problem.

You might want to try that on the live server (as an ordinary user) e.g. http://loc.csisdmz.ul.ie/SOLAS-Match/43/privateProfile/ with the 43 replaced by the uer you are trying to edit... it should give a red error...

Call to a member function getLanguagePreference() on a non-object in /repo/SOLAS-Match/ui/RouteHandlers/UserRouteHandler.class.php on line 761

    Alan.

**Comment by spaceindaver** [comment]
Hey Alan, I gave a quick look at this procedure (UserRouteHandler line 761) and it seems it is dereferencing a NULL object. On line 733 there is a call to getPersonalInfo which will validate the currently logged in user to ensure they have the required permissions to access that user's personal info. If you do not have access then it will return NULL and log the error. As a result the function should be changed so that the user are redirected back to the home page with an appropriate error message in the catch block instead of allowing the function to continue (and eventually dereferencing the NULL object). Hope that helps :-)

**Comment by alanbarrett** [comment]
Yes thanks! I found that... But I decided to postpone fixing as the only
way a user can get into that situation is if they craft a URL to get to
that page without going through the UI which will not allow them go there
(or rather will not present them with a link to go there).

I will follow your suggestion the next time I am in that part of the code.

Thanks!

    Alan.
