### ISSUE TITLE
Cannot download translation

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#1213]
I cannot seem to download the completed translation for this task: http://trommons.org/org/105/task/9544/complete/

When I go to download the source file for the proofreading task, which should be the translation, I get the original English file.

**Comment by Paulina-Rosetta** [comment]
Turns out I'm also unable to upload the translated file

**Comment by alanbarrett** [comment]
I have a plan to put in error logging for uploading of a file to see if it fails... this is a very big file... I have not had a chance to do this yet. So I have no solution.

    Alan.

**Comment by alanbarrett** [comment]
I finally got around to adding log information that should help track down what is happening, if/when this occurs again... Please let me know.

    Alan,

**Comment by alanbarrett** [comment]
New occurrence of similar issue from @Paulina-Rosetta...

We’re trying to download a file from Trommons but we get this error message: Warning! We could not find the requested file on our system. Requested file type: latest task file version. Please contact us at info@trommons.org with details of this problem.
It’s the proofread file we want to download but even when we try the translation, we get the same error.
 
Proofreading task: http://trommons.org/task/14722/view/
 
Translation task: http://trommons.org/task/14721/view/

Note it is also "The Great Plant Hunt- Identikit", maybe another large file?

    Alan.

**Comment by alanbarrett** [comment]
Immediate cause...

        $ret = file_put_contents($destinationPath, $file) ? 1 : 0;
gives...
PHP Fatal error:  Allowed memory size of 524288000 bytes exhausted (tried to allocate 139736395 bytes) in /repo/SOLAS-Match/api/v0/IO.php on line 457

    Alan.

**Comment by Paulina-Rosetta** [comment]
Thanks Alan. Is there any way we can get at the file?

**Comment by alanbarrett** [comment]
When I get home, I will check again we have nothing on the site.

    Alan.

**Comment by Paulina-Rosetta** [comment]
All good – we got the files! J Will I share them with you so you can put them up on the site?

**Comment by alanbarrett** [comment]
Yes please share with me (on Google Drive?). Please make sure to indicate
which one is which task.

   Alan.

**Comment by Paulina-Rosetta** [comment]
Here’s the link to the proofread file on Google Drive – I don’t have the translation. https://drive.google.com/a/therosettafoundation.org/file/d/0B6IDsYkaXI1ocWhteDIxcHBnTkU/view?usp=sharing

**Comment by alanbarrett** [comment]
I have uploaded that file to...
/repo/SOLAS-Match/backup/uploads/proj-4421/task-14722/v-1/The-Great-Plant-Hunt-Identikit.docx

That fixes (assuming the file is the correct one) the Proofread Task.

    Alan.

**Comment by alanbarrett** [comment]
I have modified the php.ini setting to
memory_limit = 1000M
, restarted and looked at process memory use (for normal day to day use). All seems OK.

The new Memory limit per PHP script invocation should be plenty to cover these very big files. It seems to be that at most when uploading an output file the UI would have 4 copies of the file string and the API at most 6 copies (giving a maximum for file storage in RAM of 870 MB). I had previously based the memory limit on 3 copies for the UI and I had not realised the API could use so much. In fact however, based on the PHP error, which only fell at the final hurdle, the value of 6 must be an overestimate (I do not know if or when a string is copied for each function call).

It would be possible to recode to reduce the number of copies. It would also be possible to catch and propagate the error upwards, but I am not sure what that would buy as Trommons in currently coded.

Anyway, I believe the issue is solved. We have 16GB of RAM, so there is plenty of physical memory and on top of that virtual memory which does not seem to be needed.

    Alan.
