### ISSUE TITLE
Cannot delete user

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#1223]
I'm trying to remove the user account of an an org member that no longer works with the org. I've tried twice - I click Delete User Account, get taken back to the home page (now logged out) but when I log back in to check the account is still there. http://trommons.org/8379/profile/

**Comment by Paulina-Rosetta** [comment]
Tried 2 more things. I revoked organisation membership and tried to dekete the account but still no luck. I then tried to delete her user the Delete User field on the Admin page but still nothing. She's undeletable :-o

**Comment by alanbarrett** [comment]
This did not work because the User has "TaskViews". As a short term solution I have deleted those records and was then able to delete the User.

There is an obvious proper fix...

Change: CONSTRAINT `FK_task_viewed_user` FOREIGN KEY (`user_id`) REFERENCES `Users` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE
To:     CONSTRAINT `FK_task_viewed_user` FOREIGN KEY (`user_id`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE

This would delete the "TaskViews" automatically when the "User" is deleted. However whoever designed that table very explicitly wrote "NO ACTION"

"TaskUnclaims" table has same issue ("NO ACTION" is not used anywhere else).

It seems that the change is a no brainer... But I am worried that someone designed the table this way for some reason... So I am going to hold off doing a Database Procedure change. Maybe I am just being too careful.

    Alan.

**Comment by spaceindaver** [comment]
Hey Alan, that seems like a reasonable change to me. There is no value in storing task views or tasks that have been unclaimed for users that no longer exist. If you do think the data is valuable then it could be worthwhile adding a deleted user account with a static ID and updating all the tables to point to that user whenever a user is deleted. That way you will still be tracking the view (for example if you are displaying the view count anywhere) and keeping the database consistent.

The TaskViews table was created after I left though so maybe @Wasala  would know why it was a NO ACTION instead. I know that the TaskUnclaims table was only created to prevent a task from appearing in a person's task stream if they have already refused to do the task. Since that user no longer exists I don't see any problem with cascading the delete operation.

Hope that helps :-)

**Comment by alanbarrett** [comment]
OK I will do that next week, but I will wait to hear from @Wasala first.

    Alan.

**Comment by alanbarrett** [comment]
As well as @Wasala (https://github.com/TheRosettaFoundation/SOLAS-Match/commit/e0fb862b36e5d51617120b4bcbe77918a838c07c) @TheIceMageX50 previously implemented the other case: https://github.com/TheRosettaFoundation/SOLAS-Match/commit/a257ed13c437e3407fb621c165f2bb9af69c9260

    Alan.

**Comment by alanbarrett** [comment]
Fixed by commit db76511b2bad991ca816a7496c228fdc2573fec2 and ALTER statements to Database

**Comment by Wasala** [comment]
@alan Apologies for the delayed response and not being able to contribute actively. The task views tables was implemented mainly for the purpose of data mining: #1118. While I have done a mistake in the SQL query specifying "NO ACTION" (or I had actually forgotten the real reason for doing so by now), the only disadvantage of "CASCADE" operation is that we will loose some data to track the task view behaviors of people who subsequently deleted their accounts. Actually, @spaceindaver had suggested a better idea in #937 to move all the data mining focused tables into a new database. I think this is a good idea so that we can preserve useful data in that database (while getting rid of non-essential data in the live database).
